import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  container: { flex: 1, backgroundColor: '#0f0f1a' },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#1e1e3a',
  },
  headerTitle: { fontSize: 20, fontWeight: '700', color: '#fff' },
  logoutBtn: { backgroundColor: '#2a2a4a', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8 },
  logoutBtnText: { color: '#ccc', fontSize: 13 },
  alertError: { backgroundColor: 'rgba(239,68,68,0.1)', borderColor: 'rgba(239,68,68,0.3)', borderWidth: 1, margin: 10, borderRadius: 8, padding: 10 },
  alertSuccess: { backgroundColor: 'rgba(34,197,94,0.1)', borderColor: 'rgba(34,197,94,0.3)', borderWidth: 1, margin: 10, borderRadius: 8, padding: 10 },
  alertText: { color: '#eee', fontSize: 13, textAlign: 'center' },
  tabBar: { borderBottomWidth: 1, borderBottomColor: '#1e1e3a', maxHeight: 50 },
  tabBarContent: { paddingHorizontal: 8 },
  tab: { paddingHorizontal: 16, paddingVertical: 14 },
  tabActive: { borderBottomWidth: 2, borderBottomColor: '#667eea' },
  tabText: { color: '#666', fontSize: 14 },
  tabTextActive: { color: '#667eea', fontWeight: '600' },
  tabContent: { padding: 16, paddingBottom: 40 },
  sectionTitle: { fontSize: 18, fontWeight: '600', color: '#fff', marginBottom: 16 },
  //── Dashboard ──
  statsRow: { flexDirection: 'row', gap: 12, marginBottom: 20 },
  statCard: { flex: 1, backgroundColor: '#1a1a2e', borderRadius: 12, padding: 20, alignItems: 'center', borderWidth: 1, borderColor: '#2a2a4a' },
  statNumber: { fontSize: 36, fontWeight: '700', color: '#667eea' },
  statLabel: { fontSize: 13, color: '#888', marginTop: 4 },
  refreshBtn: { backgroundColor: '#1e1e3a', borderRadius: 10, padding: 14, alignItems: 'center' },
  refreshBtnText: { color: '#aaa', fontSize: 14 },
  //── Form ──
  formGroup: { marginBottom: 14 },
  label: { color: '#aaa', fontSize: 13, marginBottom: 6 },
  input: { backgroundColor: '#0f0f1a', borderWidth: 1, borderColor: '#2a2a4a', borderRadius: 10, color: '#fff', padding: 12, fontSize: 15 },
  chipRow: { marginTop: 4 },
  chip: { backgroundColor: '#1a1a2e', borderWidth: 1, borderColor: '#2a2a4a', borderRadius: 20, paddingHorizontal: 14, paddingVertical: 8, marginRight: 8 },
  chipActive: { backgroundColor: '#667eea', borderColor: '#667eea' },
  chipText: { color: '#888', fontSize: 13 },
  chipTextActive: { color: '#fff', fontWeight: '600' },
  submitBtn: { backgroundColor: '#667eea', borderRadius: 10, padding: 16, alignItems: 'center', marginTop: 12 },
  submitBtnText: { color: '#fff', fontSize: 15, fontWeight: '600' },
  //── Card ──
  card: { backgroundColor: '#1a1a2e', borderRadius: 12, padding: 14, marginBottom: 10, borderWidth: 1, borderColor: '#2a2a4a' },
  cardRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 },
  cardTitle: { color: '#fff', fontSize: 15, fontWeight: '600', flex: 1 },
  cardSub: { color: '#888', fontSize: 13, marginBottom: 8 },
  badge: { backgroundColor: '#2a2a4a', borderRadius: 6, paddingHorizontal: 8, paddingVertical: 3, marginLeft: 8 },
  badgeText: { color: '#aaa', fontSize: 11 },
  cardActions: { flexDirection: 'row', gap: 8, marginTop: 8 },
  cardBtn: { backgroundColor: '#2a2a4a', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 6 },
  cardBtnDanger: { backgroundColor: 'rgba(239,68,68,0.1)', borderWidth: 1, borderColor: 'rgba(239,68,68,0.3)' },
  cardBtnText: { color: '#aaa', fontSize: 13 },
  cardBtnTextDanger: { color: '#ef4444' },
  //── Modal ──
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.7)', justifyContent: 'flex-end' },
  modalBox: { backgroundColor: '#1a1a2e', borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 24, borderTopWidth: 1, borderColor: '#2a2a4a', maxHeight: '85%' },
  modalTitle: { fontSize: 18, fontWeight: '700', color: '#fff', marginBottom: 4 },
  modalSubtitle: { color: '#888', fontSize: 13, marginBottom: 16 },
  modalActions: { flexDirection: 'row', gap: 12, marginTop: 16 },
  modalCancelBtn: { flex: 1, backgroundColor: '#2a2a4a', borderRadius: 10, padding: 14, alignItems: 'center' },
  modalCancelBtnText: { color: '#aaa', fontSize: 14 },
});
