import { StyleSheet } from 'react-native';
import { colors, radius, spacing, MIN_TOUCH } from '../theme';

export const styles = StyleSheet.create({
  flex: { flex: 1 },
  container: { flex: 1, backgroundColor: colors.background },
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing.lg,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.borderSubtle,
  },
  headerTitle: { fontSize: 20, fontWeight: '700', color: colors.text },
  logoutBtn: { minWidth: 88 },
  banners: { paddingHorizontal: 10, paddingTop: 10 },
  tabBar: { borderBottomWidth: 1, borderBottomColor: colors.borderSubtle, flexGrow: 0 },
  tabBarContent: { paddingHorizontal: spacing.sm },
  tab: { minHeight: MIN_TOUCH, justifyContent: 'center', paddingHorizontal: spacing.lg },
  tabActive: { borderBottomWidth: 2, borderBottomColor: colors.primary },
  tabText: { color: colors.textMuted, fontSize: 14 },
  tabTextActive: { color: colors.primary, fontWeight: '600' },
  tabContent: { padding: spacing.lg, paddingBottom: 40 },
  sectionTitle: { fontSize: 18, fontWeight: '600', color: colors.text, marginBottom: spacing.lg },
  // Dashboard
  statsRow: { flexDirection: 'row', gap: spacing.md, marginBottom: 20 },
  statCard: {
    flex: 1,
    backgroundColor: colors.surface,
    borderRadius: radius.lg - 4,
    padding: 20,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: colors.border,
  },
  statNumber: { fontSize: 36, fontWeight: '700', color: colors.primary },
  statLabel: { fontSize: 14, color: colors.textSecondary, marginTop: 4 },
  // Cards
  card: {
    backgroundColor: colors.surface,
    borderRadius: radius.lg - 4,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: colors.border,
  },
  cardRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 },
  cardTitle: { color: colors.text, fontSize: 16, fontWeight: '600', flex: 1 },
  cardSub: { color: colors.textSecondary, fontSize: 14, marginBottom: spacing.sm },
  badge: {
    backgroundColor: colors.surfaceRaised,
    borderRadius: 6,
    paddingHorizontal: spacing.sm,
    paddingVertical: 3,
    marginLeft: spacing.sm,
    overflow: 'hidden',
    color: colors.textSecondary,
    fontSize: 12,
  },
  cardActions: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm, marginTop: spacing.sm },
  cardBtn: { minWidth: 72 },
  empty: { color: colors.textSecondary, fontSize: 15, textAlign: 'center', marginTop: 32 },
  // Modal
  modalOverlay: { flex: 1, backgroundColor: colors.overlay, justifyContent: 'flex-end' },
  modalBox: {
    backgroundColor: colors.surface,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    padding: spacing.xl,
    borderTopWidth: 1,
    borderColor: colors.border,
    maxHeight: '90%',
  },
  modalTitle: { fontSize: 18, fontWeight: '700', color: colors.text, marginBottom: 4 },
  modalSubtitle: { color: colors.textSecondary, fontSize: 14, marginBottom: spacing.lg },
});
